### ISSUE TITLE
Change navbar behaviour

### ISSUE THREAD

**Issue by cjnbennett** [codersforcauses/starick#104]
## Basic Information
Currently, clicking on a navbar item with subitems will cause the submenu to unfurl. On most sites (including the current Starick site), the usual navbar behaviour is to go to some root page when clicking on the navbar item itself, and to unfurl the submenu on scroll. The behaviour should be changed to reflect this.

## Other Information
See #101 for an example / test case where this matters.

**Comment by seraph1201** [comment]
made redundant by [issue 71](https://github.com/codersforcauses/starick/issues/71)
