### ISSUE TITLE
Navbar dropdown menu layering issue

### ISSUE THREAD

**Issue by junhyap** [codersforcauses/starick#133]
## Basic Information
Currently, the navbar dropdown menu is layered behind some content on the page, this makes it difficult to access different areas of the website on certain pages.

![image](https://github.com/codersforcauses/starick/assets/6574274/4a335afa-e414-4f62-acee-f48b12a3f25e)

## Other Information
**[Are there any additional information that we should know about?]**

**Comment by Julie-Salazar** [comment]
should be a simple layering className="..... z-10" just need to rearrage divs

**Comment by seraph1201** [comment]
made redundant due to [issue 71](https://github.com/codersforcauses/starick/issues/71)
