### ISSUE TITLE
Update donation and op shop pages to match figma

### ISSUE THREAD

**Issue by HuxleyBerry** [codersforcauses/starick#138]
These pages:
- Donations
- Starick Op Shop
- Op Shop Donations

**Comment by seraph1201** [comment]
To be added:
In the donations page, add a button that links externally to Starick's Good2Give profile.

Placement: Link to Good2Give Workplace Giving platform to be added to donations page as a button. To be placed below paypal section, feel free to copy the general formatting of the paypal section. (eg image on one side, text and button on the other side)
Functionality: This button will link externally to their Good2Give profile.

**Comment by seraph1201** [comment]
Frontend for donations page: [issue 126](https://github.com/codersforcauses/starick/issues/126)
see src-> pages -> donations
