### ISSUE TITLE
Paypal donation component

### ISSUE THREAD

**Issue by cjnbennett** [codersforcauses/starick#16]
# Basic Information
Make a Paypal donation component to be used on various website pages. See the [current donation page](https://www.starick.org.au/get-involved/donate/) - particularly the "Make a One-Off Donation (Paypal)".

# Other Information

# Related Issues
Will be used in #4 and #8

**Comment by MoeBuTa** [comment]
Todos: Customise donation amount, database storage

**Comment by seraph1201** [comment]
Due to requests of the client, Stripe will be used in lieu of Paypal. See [issue 126](https://github.com/codersforcauses/starick/issues/126).
