### ISSUE TITLE
Chatbot backend

### ISSUE THREAD

**Issue by cjnbennett** [codersforcauses/starick#25]
## Basic Information
Implement the backend for the chatbot. This will include:
- [x] Adding API endpoints to perform ChatGPT calls
- [x] Use the OpenAI "Assistants" feature to create a custom chatbot GPT which is focused on providing information about methods of donation
  - See [here](https://platform.openai.com/docs/assistants/overview) for information about Assistants
  - The bot should use information from the existing donations pages on Starick's site for context. We'll try aggregate this information into a single document for ease of reference (not done yet, will comment when done)
- [ ] Prompt engineering to ensure good chat flow
- [x] Integrating with the frontend

We will provide you with an OpenAI key upon request if you're working on this issue, let us know

## Other Information
See #23 for an idea of how this will integrate into the frontend

**Comment by cjnbennett** [comment]
Prompt engineering needed to finish this issue

**Comment by dimmerz92** [comment]
Accidentally closed, will still require prompt engineering

**Comment by dimmerz92** [comment]
Information on how to use the API is in the README.
Provides a single response (not streamed).

**Comment by seraph1201** [comment]
Due to facebook no longer continuing to support messenger plugin(and following consultation with Starick), this issue/feature will be discontinued.
