### ISSUE TITLE
HomePage Facebook plugin 

### ISSUE THREAD

**Issue by Julie-Salazar** [codersforcauses/starick#40]
## Basic Information

back end for plug in requires access token which needs login details for the starick facebook (Proj managers will ask them for it) the sooner we have it the better. 

once this is gotten iframe can be used to embed into homepage (since we only need a scrolling sandbox style page)

## Other Information
`const fetchData = async () => {
      try {
        const response = await fetch('https://graph.facebook.com/v12.0/StarickServices/posts?access_token=THEFB_ACCESS_TOKEN');
        const data = await response.json();
        setFeedData(data.data);`

**Comment by Julie-Salazar** [comment]
#17

**Comment by cjnbennett** [comment]
Nice code snippet. Just for reference, I believe this code should go on the backend (as an API route). While the Facebook docs aren't entirely clear, the impression I get by reading the [Login Security](https://developers.facebook.com/docs/facebook-login/security) page is that app tokens should either be server-side secrets, or if you want to use them client-side then they should be programmatically generated and have a short expiry time. See also the [Access Token Guide](https://developers.facebook.com/docs/facebook-login/guides/access-tokens/) page which seems to imply that access tokens should be secrets (as opposed to other tokens listed there, e.g. client tokens).

**Comment by cjnbennett** [comment]
Now that CFC has completed Facebook business verification, we can proceed with this. I have an *app secret token* which I can share with whoever works on this issue (contact me and I'll add you to the Facebook app / give you the token). There's a bit of work that needs to be done other than the code given above - the above code requires an *app access token*. The access token can be programmatically derived from the secret token, as outlined in the [Facebook documentation](https://developers.facebook.com/docs/facebook-login/security#appsecret). These calculations should happen on the backend.
