### ISSUE TITLE
Information pages

### ISSUE THREAD

**Issue by cjnbennett** [codersforcauses/starick#5]
# Basic Information
Recreating static information pages on the site:
- [Recognising the signs](https://www.starick.org.au/what-is-domestic-violence/recognising-the-signs/)
- [FAQ](https://www.starick.org.au/what-is-domestic-violence/faq/)

# Other Information

**Comment by RadioArsenic** [comment]
for FAQ page, see [issue 14](https://github.com/codersforcauses/starick/issues/14) for how to add in the in-page nav once that's merged in (msg me if you need help)
