### ISSUE TITLE
Disclaimer Component

### ISSUE THREAD

**Issue by K-Straiton** [codersforcauses/starick#60]
## Basic Information
Create a component for the disclaimer that can be found at the bottom of a few pages that contain resources

## Other Information
**[Are there any additional information that we should know about?]**

**Comment by cjnbennett** [comment]
I think @MoeBuTa said that this was done in issue #42? I'm not sure, worth checking to avoid duplication of work

**Comment by MoeBuTa** [comment]
> I think @MoeBuTa said that this was done in issue #42? I'm not sure, worth checking to avoid duplication of work

yeah i've done the disclaim. and now i've merge it into PR for issue#8 https://github.com/codersforcauses/starick/pull/75/files#diff-2c9c0222549197128126dd09ef557c4d610ddb7e858c711ca11f08e0d059924c
