### ISSUE TITLE
About us pages

### ISSUE THREAD

**Issue by cjnbennett** [codersforcauses/starick#7]
# Basic Information
Recreate the [About Us pages](https://www.starick.org.au/about/).

# Other Information
As there are several subpages here, it may make sense to create subissues for this issue.

**Comment by RadioArsenic** [comment]
### Update:
From what I can see, issues have been created for the [job opps](https://github.com/codersforcauses/starick/issues/10), [contact us](https://github.com/codersforcauses/starick/issues/9), and [our stories](https://github.com/codersforcauses/starick/issues/92) pages. 

I've created subissues for the [our people](https://github.com/codersforcauses/starick/issues/93), [our supporters](https://github.com/codersforcauses/starick/issues/94), and [our publications](https://github.com/codersforcauses/starick/issues/95) pages, and another for the [timeline component](https://github.com/codersforcauses/starick/issues/96) for this page as that alone feels like a large task, and then this issue can become just the About Us / About Starick page.
