### ISSUE TITLE
Edit Nav bar to match Figma

### ISSUE THREAD

**Issue by K-Straiton** [codersforcauses/starick#71]
## Basic Information
The nav bar has been slightly changed on the Figma. Edit the nav bar to match.

## Other Information
**[Are there any additional information that we should know about?]**

**Comment by seraph1201** [comment]
@yunho7687 Just some updates from the client,
To be added:
**Placement:** Dedicated 'News' button to be inserted between "About Us" and "Op Shop" in the navbar
<img width="461" alt="Screenshot 2024-02-24 at 11 27 21 am" src="https://github.com/codersforcauses/starick/assets/104136188/d1eeef8d-9345-41f4-bb4a-edf343b7d26f">

It would just follow the same styling as everything else.
**Functionality:** This button will link directly to the most recent newsletter. Here's the link for reference: [Current Newsletter](https://us20.campaign-archive.com/?u=fd9ee23110367fb6d7afdc749&id=bc2242df48).
